#!/bin/bash
#/usr/bin/prime-offload
#xrandr --auto
feh --bg-fill "$(< "${HOME}/.cache/wal/wal")" 
setxkbmap es &

/home/$USER/.config/polybar/launch.sh &

xsetroot -cursor_name left_ptr &

killall sxhkd

sxhkd & 

#picom --fading --experimental-backend --config /home/$USER/.config/picom/picom.conf &

#killall wallpaper
#killall sleep

#killall easystroke
#easystroke &

#killall dunst
#dunst -c /home/$USER/.config/dunst/dunstrc &

killall xfce4-notifyd
/usr/lib/xfce4/notifyd/xfce4-notifyd &

nm-applet &

blueman-applet &

wmname LG3D &

xclip &

#wal -n -i /home/$USER/fondos/wolf-1626952035369-7116.jpg

# source the colors.
. "${HOME}/.cache/wal/colors.sh" &

# Set the border colors.
bspc config normal_border_color "$color3"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1"
## Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

bspc config presel_feedback_color "$color1"
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          5

bspc config automatic_scheme	spiral
bspc config border_radius	8
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true



#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gtksu state=floating
bspc rule -a XTerm state=floating

 
picom --detect-rounded-corners --fading --config /home/$USER/.config/picom/picom.conf &
#killall compfy
#compfy &
#killall glava
#sleep 3 && glava --desktop --force-mod=graph &
#cmleon &
mcontrolcenter &
