--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/isaac/fondos/vinlandsaga/frame1189.png"

-- Special
background="#120707"
foreground="#c3c1c1"
cursor="#c3c1c1"

-- Colors
color0="#120707"
color1="#A35A5B"
color2="#D0745D"
color3="#E4883F"
color4="#EB9A69"
color5="#FBC876"
color6="#F7B185"
color7="#c3c1c1"
color8="#6a5656"
color9="#A35A5B"
color10="#D0745D"
color11="#E4883F"
color12="#EB9A69"
color13="#FBC876"
color14="#F7B185"
color15="#c3c1c1"
