# Shell variables
# Generated by 'wal'
wallpaper="/home/isaac/fondos/vinlandsaga/frame1189.png"

# Special
background='#120707'
foreground='#c3c1c1'
cursor='#c3c1c1'

# Colors
color0='#120707'
color1='#A35A5B'
color2='#D0745D'
color3='#E4883F'
color4='#EB9A69'
color5='#FBC876'
color6='#F7B185'
color7='#c3c1c1'
color8='#6a5656'
color9='#A35A5B'
color10='#D0745D'
color11='#E4883F'
color12='#EB9A69'
color13='#FBC876'
color14='#F7B185'
color15='#c3c1c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
