--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/isaac/fondos/walle/wall-e-2020-4k-0l.jpg"

-- Special
background="#0C0F17"
foreground="#abc1d9"
cursor="#abc1d9"

-- Colors
color0="#0C0F17"
color1="#264169"
color2="#27437A"
color3="#465879"
color4="#2D4D88"
color5="#3B63A3"
color6="#4870AB"
color7="#abc1d9"
color8="#778797"
color9="#264169"
color10="#27437A"
color11="#465879"
color12="#2D4D88"
color13="#3B63A3"
color14="#4870AB"
color15="#abc1d9"
